### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by asssiheh** [The-Dingos/MinecraftAlternateRealities#2]
Is it possible in pocket edition

**Comment by The-Dingos** [comment]
I don’t think so- I made it for Java Edition.
Just curious, how’d you find out about the his? Like Reddit or some youtuber?

**Comment by asssiheh** [comment]
Yeah a guy named not Paul GG I found the link to here so I followed it and here I am thanks for responding

**Comment by The-Dingos** [comment]
Thanks!
